# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/GIT/coa-design/cpu/cpu.srcs/sources_1/ip/RAM1_1/RAM1.xci
# IP: The module: 'RAM1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GIT/coa-design/cpu/cpu.srcs/sources_1/ip/RAM1_1/RAM1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/GIT/coa-design/cpu/cpu.srcs/sources_1/ip/RAM1_1/RAM1.xci
# IP: The module: 'RAM1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GIT/coa-design/cpu/cpu.srcs/sources_1/ip/RAM1_1/RAM1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
